export enum StorageItems {
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  AUTHENTICATED = 'AUTHENTICATED',
  COLOR_SCHEME = 'COLOR_SCHEME',
  STUDENT_PROFILE = 'STUDENT_PROFILE',
  MOCK_USERS = 'MOCK_USERS',
  MOCK_APPOINTMENT = 'MOCK_APPOINTMENT',
  USER_STORED = 'USER_STORED',
}
